title: i-be-designs
logo: /assets/img/logo.png
description: Hand Crafted and Designed Surfboards
show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal
# github:
#  owner_name: i-be-designs
